repository: ${GITHUB_REPOSITORY}
coverage:
  if: true
codeToTestRatio:
  code:
    - '**/*.ts'
    - '!**/*_test.go'
  test:
    - '**/*_test.go'
testExecutionTime:
  if: true
comment:
  if: is_pull_request
  hideFooterLink: false
summary:
  if: is_pull_request
  hideFooterLink: false
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}/todo-app
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}/todo-app