name: "lint and test"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  api-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
          registry-url: "https://npm.pkg.github.com/"
          node-version: 22
      - run: pnpm i
        shell: bash
      - run: cp .env.example .env
      - name: run app background
        run: pnpm run dev &
        shell: bash
      - run: echo 'runn'
