name: "e2e-test"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: e2e-test
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
          registry-url: "https://npm.pkg.github.com/"
          node-version: 22
      - run: pnpm i
        shell: bash
      - run: pnpm playwright install chromium
        shell: bash
      - run: pnpm playwright test --project=todo-app
        env:
          BASE_URL: https://todo-app-qajp.vercel.app
